# i3blocks config file
#
# Please see man i3blocks for a complete reference!
# The man page is also hosted at http://vivien.github.io/i3blocks
#
# List of valid properties:
#
# align
# color
# command
# full_text
# instance
# interval
# label
# min_width
# name
# separator
# separator_block_width
# short_text
# signal
# urgent

# Global properties
command=/home/$USER/.config/i3blocks/blocks/$BLOCK_NAME
separator_block_width=15
markup=none

[cpu_usage]
label=CPU
interval=10
separator=false

[memory]
label=MEM
interval=30

[disk]
label=
interval=30

[iface]
label=
color=#00FF00
interval=10

[volume]
command=/usr/share/i3blocks/volume "5%" pulse
label=♪
instance=Master
interval=once
signal=1

[battery]
label=⚡
instance=0
interval=30

[time]
command=date '+%d.%m.%Y %H:%M'
interval=5
